"""Stage the installer payload and generate payload.rc / payload_index.h.

Payload kinds: 0 = UE4SS (stock experimental build), 1 = BiggerParty, 2 = GiveSpellbook, 3 = docs, 4 = Narrator.
The Narrator companion (Narrator/companion/dist/SolastaNarrator.exe) must be built first: see Narrator/companion/narrator.py.
Run from anywhere; paths are resolved relative to this file.
"""
import os, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                       # BiggerParty/
WS = os.path.dirname(ROOT)                         # solasta2-mods/
UE4SS_SRC = sys.argv[1] if len(sys.argv) > 1 else None
if not UE4SS_SRC or not os.path.isdir(UE4SS_SRC):
    print("usage: gen_payload.py <path to extracted UE4SS folder containing dwmapi.dll and ue4ss/>"); sys.exit(1)

STAGE = os.path.join(HERE, "payload")
shutil.rmtree(STAGE, ignore_errors=True)
entries = []   # (kind, relpath)

def add_tree(src_dir, dst_prefix, kind, skip=lambda rel: False):
    for dirpath, _, files in os.walk(src_dir):
        for fn in files:
            src = os.path.join(dirpath, fn)
            rel = os.path.relpath(src, src_dir).replace("\\", "/")
            if skip(rel): continue
            dst_rel = (dst_prefix + "/" + rel) if dst_prefix else rel
            dst = os.path.join(STAGE, dst_rel.replace("/", os.sep))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
            entries.append((kind, dst_rel))

# 0: stock UE4SS (mods.txt/mods.json are rewritten by the installer)
add_tree(UE4SS_SRC, "", 0)
# 1: BiggerParty
dist = os.path.join(ROOT, "dist")
for rel in ["version.dll", "BiggerParty.ini", "ue4ss/Mods/BiggerParty/Scripts/main.lua", "ue4ss/Mods/BiggerParty/enabled.txt"]:
    src = os.path.join(dist, rel.replace("/", os.sep)); dst = os.path.join(STAGE, rel.replace("/", os.sep))
    os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy2(src, dst); entries.append((1, rel))
# 2: GiveSpellbook
gs = os.path.join(WS, "GiveSpellbook")
for rel in ["Scripts/main.lua", "enabled.txt"]:
    src = os.path.join(gs, rel.replace("/", os.sep)); dst_rel = "ue4ss/Mods/GiveSpellbook/" + rel
    dst = os.path.join(STAGE, dst_rel.replace("/", os.sep))
    os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy2(src, dst); entries.append((2, dst_rel))
# 3: docs
shutil.copy2(os.path.join(dist, "README.txt"), os.path.join(STAGE, "BiggerParty-README.txt")); entries.append((3, "BiggerParty-README.txt"))
# 4: Narrator (mod + companion program)
nr = os.path.join(WS, "Narrator")
for src_rel, dst_rel in [("Scripts/main.lua", "ue4ss/Mods/Narrator/Scripts/main.lua"), ("enabled.txt", "ue4ss/Mods/Narrator/enabled.txt"),
                         ("companion/dist/SolastaNarrator.exe", "Narrator/SolastaNarrator.exe")]:
    src = os.path.join(nr, src_rel.replace("/", os.sep)); dst = os.path.join(STAGE, dst_rel.replace("/", os.sep))
    if not os.path.exists(src): print("missing " + src + " (build the Narrator companion first)"); sys.exit(1)
    os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy2(src, dst); entries.append((4, dst_rel))

# zero-byte files (enabled.txt markers) cannot be embedded as resources: give them one byte
for _, rel in entries:
    fp = os.path.join(STAGE, rel.replace("/", os.sep))
    if os.path.getsize(fp) == 0:
        with open(fp, "w") as f: f.write("1" + chr(10))
entries.sort(key=lambda e: (e[0], e[1]))
with open(os.path.join(HERE, "payload.rc"), "w", encoding="ascii") as rc, open(os.path.join(HERE, "payload_index.h"), "w", encoding="ascii") as h:
    h.write("// generated by gen_payload.py - do not edit\n#pragma once\n")
    h.write("struct PayloadFile { int id; const wchar_t* relPath; int kind; };\n")
    h.write("static const PayloadFile kPayload[] = {\n")
    for i, (kind, rel) in enumerate(entries):
        rid = 1000 + i
        abs_path = os.path.join(STAGE, rel.replace("/", os.sep)).replace("\\", "\\\\")
        rc.write(f'{rid} RCDATA "{abs_path}"\n')
        h.write(f'    {{ {rid}, L"{rel}", {kind} }},\n')
    h.write("};\n")
    h.write(f"static const int kPayloadCount = {len(entries)};\n")
total = sum(os.path.getsize(os.path.join(STAGE, rel.replace('/', os.sep))) for _, rel in entries)
print(f"staged {len(entries)} files, {total/1e6:.1f} MB")
